services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ask2watch
      POSTGRES_USER: ask2watch
      POSTGRES_PASSWORD: ask2watch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
